apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: pypi
  name: pypi
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/jrigsbee/pypi:latest
    from:
      kind: DockerImage
      name: quay.io/jrigsbee/pypi:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
