apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypi
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: pypi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
  volumeMode: Filesystem
